export const TECH_STACK = {
  DENO: "Deno",
  FRESH: "Fresh",
  PREACT: "Preact",
  NODEJS: "Node.js",
  TYPESCRIPT: "TypeScript",
  NEXTJS: "Next.js",
  REACT: "React",
  MONGODB: "MongoDB",
  PRISMA: "Prisma",
  POSTGRESQL: "PostgreSQL",
  AWS: "AWS",
  SST: "SST",
  VERCEL: "Vercel",
  TAILWIND: "Tailwind",
  TRPC: "tRPC",
  ALGOLIA: "Algolia",
  GRAPHQL: "GraphQL",
  DOCKER: "Docker",
  OMNI_BI: "Omni BI",
  REDUX: "Redux",
  RUBY: "Ruby",
  RUBY_ON_RAILS: "Ruby on Rails",
  SIDEKIQ: "Sidekiq",
  JAVASCRIPT: "JavaScript",
  DRIZZLE: "Drizzle",
  PYTHON: "Python",
  DJANGO: "Django",
  RAILWAY: "Railway",
  PUSHER: "Pusher",
  BUN: "Bun",
} as const;
